### ISSUE TITLE
Error running demo: Not enough values to unpack

### ISSUE THREAD

**Issue by harD2** [dfmsoares/triclustering-based-classifier#1]
I'm trying to run the demo and ran into an issue when trying to run the classifier. All other steps appeared to have worked, though there was no output to the terminal. I changed my working directory to triclustering-based-classifier-main and ran the code as stated in the demo section of your readme. 

Input 

`(base) oem@home:~/Python/triclustering-based-classifier-main$ python3 src/compute_similar_mats_tri.py demo/d1.csv demo/triclusters_d1.txt demo/sim_matrices/ Class 3 [S1, S2, S3, S4, S5, S6] []`

Output

>10
/home/oem/Python/triclustering-based-classifier-main/src/identify_triclusters.py:78: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  return ss.mode(z)[0][0]
10
/home/oem/Python/triclustering-based-classifier-main/src/identify_triclusters.py:78: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  return ss.mode(z)[0][0]
Traceback (most recent call last):
  File "/home/oem/Python/triclustering-based-classifier-main/src/compute_similar_mats_tri.py", line 70, in <module>
    matrix, cols = idt.compute_distance_matrix(ps_tr, triclusters, cat_feats, cont_feats, corr=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/Python/triclustering-based-classifier-main/src/identify_triclusters.py", line 212, in compute_distance_matrix
    dist_set[(pat, tric_names[nTr], i)] = dot_product(list(a),list(b))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/Python/triclustering-based-classifier-main/src/identify_triclusters.py", line 278, in dot_product
    b1, b2 = lst2
    ^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by dfmsoares** [comment]
Fixed. It was an error regarding updates on numpy function output format. Thanks
